### ISSUE TITLE
[Feat] 자리표 찍기 기획 수정사항 반영

### ISSUE THREAD

**Issue by byoth** [DeveloperAcademy-POSTECH/MacC-Team6-QED#106]
# Description
소소하게 기획 바뀐 것들 작업

# Todos

## 공통
- [x] 무대 앞 표시
- [x] 토스트
- [x] 색상 이상한 거 조정
- [x] (개인 판단) 햅틱

## 대형짜기
- [x] 가사 입력 버튼 디테일
- [x] 가사 입력 모달 디테일
- [x] 동선 프리셋 자동 열기
- [x] 포메이션 넘버링

## 세부동선
- [x] 이전/이후 스타일 변경
