### ISSUE TITLE
[Feat] PerformanceSetting

### ISSUE THREAD

**Issue by OLING99** [DeveloperAcademy-POSTECH/MacC-Team6-QED#11]
# Description
Performance Setting (author, headcount, title, playable)

# Tasks
- [x] model 세팅
- [x] 노래, 아티스트 검색 viewmodel 생성
- [x] 프로젝트 이름 view 구현
- [x] 인원 수 선택 view 구현
- [x] 노래 선택 view 구현
