### ISSUE TITLE
[Feat] 메인 플로우 구현

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MacC-Team6-QED#14]
# Description
 메인 화면의 플로우를 구현합니다

# Tasks
- [ ] 네비바(개인 설정 페이지로 이동)
- [ ] 자리표 만들기로 이동
- [ ] 최근 나의 자리표
