### ISSUE TITLE
[Feat] 대형 보기 기능 추가

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MacC-Team6-QED#34]
# Description
전체 대형 보기 데이터 호출 방식 변경 및 기능, 컴포넌트 추가

# Task
- [ ] 전체 대형 보기 리스트 삭제 처리
- [ ] useCase로 전체 대형 보기에 필요한 더미 데이터 호출
- [ ] 대형 보기 동선 이동 애니메이션 처리
- [ ] 디렉터 노트 컴포넌트 구현
- [ ] 가사 입력 컴포넌트 구현
