### ISSUE TITLE
[Feat]메인 리팩토링

### ISSUE THREAD

**Issue by OLING99** [DeveloperAcademy-POSTECH/MacC-Team6-QED#56]
# Description
 메인화면 리팩토링

# Tasks
- [x] 메인 뷰 퍼포먼스 없을 때 화면
- [x] 최근 제작 동선 컴포넌트화
- [x] 퍼포먼스리스트리딩 뷰 화면 수정
- [x] titleSetupView 리팩토링
- [x] HeadcountSetupView 리팩토링
- [x] MusicSetupView 리팩토링
