### ISSUE TITLE
[Feat] 자리표 보기 리펙토링

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MacC-Team6-QED#58]
# Description
 자리표 보기 리펙토링

# Tasks
- [ ] 전체 대형 보기 리스트 삭제
- [ ] 디렉터 노트 시트 버그 픽스
- [ ] playable 뷰 리펙
- [ ] 이전동선 보기 버그 픽스
- [ ] 재생 끊기지 않게 수정
- [ ] 확대버튼
- [ ] 전체 대형/ 상세 대형에서 자리표 따기로 이동
