### ISSUE TITLE
[Feat] 기능 어셈블

### ISSUE THREAD

**Issue by UIMAPH** [DeveloperAcademy-POSTECH/MacC-Team6-QED#60]
# Description
내부 쇼케이스 전까지 구현했던것들 합치는 작업

# Tasks
- [ ] 올링의 Performance Setting에서 데이터 정상적으로 pass하는지 확인
- [ ] 각 flow에서 firestore와 상호작용이 잘 되는 지 확인
- [ ] 만들었던 Perforamance가 잘 보여지는 확인
