### ISSUE TITLE
[Feat] 가사관련된 법적 근거 및 가능성 확인

### ISSUE THREAD

**Issue by UIMAPH** [DeveloperAcademy-POSTECH/MacC-Team6-QED#68]
# Description
 ㅈㄱㄴ

# Tasks
- [ ] 개인사업자의 가사사용 루트 및 방법
- [ ] 접근해야할 업체 리스트업
- [ ] 업체에게 요구하기 위한 근거 리스트업
