### ISSUE TITLE
[Feat] 자리표 찍기 우선순위 개선 추가 작업

### ISSUE THREAD

**Issue by byoth** [DeveloperAcademy-POSTECH/MacC-Team6-QED#89]
# Tasks
- [x] 스테이지 그리드 (36*22) 구현
- [x] 프레임 삭제/복제 롱프레스 -> 탭 변경
- [x] 인물 수정 롱프레스 -> 탭 변경
- [x] (개인 판단) 내비게이션 이후 오브젝트 잘 안 나타나는 버그 수정
- [x] (개인 판단) 프리셋 찍기 크래시 수정
