### ISSUE TITLE
[Feat] Main, PerformanceSetting, PerformanceListReading 리팩

### ISSUE THREAD

**Issue by OLING99** [DeveloperAcademy-POSTECH/MacC-Team6-QED#95]
# Description
Main, PerformanceSetting, PerformanceListReading 리팩

# Tasks
- [x] listCardView detail 수정
- [x] back -> navigation으로 화면 쌓이는 오류 수정
- [x] music cell albumcover 추가
- [ ] title setup textfield 초기화
